nroho_base_default:
    pattern:  /
    defaults: { _controller: BaseNrohoBundle:Default:index }

nroho_base_aide:
    pattern: /aide
    defaults: { _controller: BaseNrohoBundle:Default:aide }

nroho_base_add_select:
    pattern: /add/{first}/{seconde}
    defaults: { _controller: BaseNrohoBundle:Search:addSelect }
    requirements:
        first:   \d+
        seconde: \d+

nroho_base_top:
    pattern: /top/{page}
    defaults: { _controller: BaseNrohoBundle:Search:top, page: 8 }

nroho_base_search:
    pattern: /search/{first}/{seconde}
    defaults: { _controller: BaseNrohoBundle:Search:search }
    requirements:
        first:   \d+
        seconde: \d+

nroho_base_search_destination:
    pattern: /search/{start}
    defaults: { _controller: BaseNrohoBundle:Search:destination }
    requirements:
        start: \d+

nroho_base_recherche:
    pattern: /recherche
    defaults: { _controller: BaseNrohoBundle:Search:recherche }

nroho_base_produit:
    pattern: /produit/{id}/
    defaults: { _controller: BaseNrohoBundle:Default:product }
    requirements:
        id:  \d+

nroho_base_product:
    pattern: /product/{id}/
    defaults: { _controller: BaseNrohoBundle:Default:product }
    requirements:
        id:  \d+

nroho_base_ajout:
    pattern: /ajout
    defaults: { _controller: BaseNrohoBundle:Default:ajout }

nroho_base_add:
    pattern: /add
    defaults: { _controller: BaseNrohoBundle:Default:add }

nroho_base_edit:
    pattern: /edit/{id}
    defaults: { _controller: BaseNrohoBundle:Default:edit }
    requirements:
        id:  \d+

nroho_base_remove:
    pattern: /remove/{id}
    defaults: { _controller: BaseNrohoBundle:Default:remove }
    requirements:
        id:  \d+

nroho_base_compte:
    pattern: /compte
    defaults: { _controller: BaseNrohoBundle:Default:compte }

nroho_base_annonce:
    pattern: /annonce
    defaults: { _controller: BaseNrohoBundle:Default:annonce }

nroho_base_demande:
    pattern: /demande
    defaults: { _controller: BaseNrohoBundle:Demande:demande }

nroho_base_demande_yes:
    pattern: /demande/yes/{id}
    defaults: { _controller: BaseNrohoBundle:Demande:yesDemande }
    requirements:
        id:  \d+

nroho_base_demande_no:
    pattern: /demande/no/{id}
    defaults: { _controller: BaseNrohoBundle:Demande:noDemande }
    requirements:
        id:  \d+

nroho_base_message:
    pattern: /message
    defaults: { _controller: BaseNrohoBundle:Message:message }

nroho_base_message_lecture:
    pattern: /message/{id}/{product}
    defaults: { _controller: BaseNrohoBundle:Message:messageid }
    requirements:
        id:  \d+
        product:  \d+

nroho_base_message_submit:
    pattern: /message/submit/{id}/{product}/{msg}
    defaults: { _controller: BaseNrohoBundle:Message:messagesubmit }
    requirements:
        id:  \d+
        product: \d+

nroho_base_profil:
    pattern: /profil/{id}
    defaults: { _controller: BaseNrohoBundle:Default:profil }
    requirements:
        id:  \d+

nroho_admin_annonce:
    pattern: /admin/annonce/
    defaults: { _controller: BaseNrohoBundle:Admin:Annonce }

nroho_admin_annonce_yes:
    pattern: /admin/annonce/yes/{id}
    defaults: { _controller: BaseNrohoBundle:Admin:yesAnnonce }
    requirements:
        id:  \d+

nroho_admin_annonce_no:
    pattern: /admin/annonce/no/{id}
    defaults: { _controller: BaseNrohoBundle:Admin:noAnnonce }
    requirements:
        id:  \d+
