parameters:
#    base_nroho.example.class: Base\NrohoBundle\Example

services:
#    base_nroho.example:
#        class: %base_nroho.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
