parameters:
#    base_nroho.example.class: Base\NrohoBundle\Example

services:
#    base_nroho.example:
#        class: %base_nroho.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    antispam:
        class:     Base\NrohoBundle\Service\Antispam\Antispam
        arguments: [50]
        #arguments: [@mailer, %locale%, 50]
