security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_manager
        custom:
            id: s4a_user.my_provider
        
        
        #in_memory:
            #memory:
                #users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: custom  #fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
            #pattern:  ^/demo/secured/login$
            #security: false

        #secured_area:
            #pattern:    ^/demo/secured/
            #form_login:
                #check_path: _security_check
                #login_path: _demo_login
            #logout:
                #path:   _demo_logout
                #target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/add, role: ROLE_USER }
        - { path: ^/message, role: ROLE_USER }
        - { path: ^/demande, role: ROLE_USER }
        - { path: ^/annonce, role: ROLE_USER }
        - { path: ^/ajout, role: ROLE_USER }
        - { path: ^/recherche, role: ROLE_USER }
        - { path: ^/compte, role: ROLE_USER }
        - { path: ^/aide, role: ROLE_USER }
        - { path: ^/product, role: ROLE_USER }
        #- { path: ^/, role: ROLE_ADMIN }
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
