<?php

namespace Base\NrohoBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Base\NrohoBundle\Entity\Product;

class ProductData extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $product1 = new Product();
        $product1->setUser($this->getReference('user1'));
        $product1->setAnimal('1');
        $product1->setArrivee('31 - Oran');
        $product1->setBlabla('1');
        $product1->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product1->setDepart('16 - Alger');
        $product1->setFilles('0');
        $product1->setFumer('0');
        $product1->setHeure('09h');
        $product1->setIp('127.0.0.1');
        $product1->setMessage('Trajet sympathique!');
        $product1->setMusique('1');
        $product1->setPlace('2');
        $product1->setPrix('200');
        $product1->setType('1');
        $product1->setValid('1');
        $product1->setVehicule('206');
        $product1->setVillea('');
        $product1->setVilleb('Kharouba');
        $product1->setVue('4');
        $product1->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product1->setJours($this->getReference('jours1'));
        $manager->persist($product1);
        
        $product2 = new Product();
        $product2->setUser($this->getReference('user2'));
        $product2->setAnimal('1');
        $product2->setArrivee('31 - Oran');
        $product2->setBlabla('1');
        $product2->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product2->setDepart('16 - Alger');
        $product2->setFilles('0');
        $product2->setFumer('0');
        $product2->setHeure('09h');
        $product2->setIp('127.0.0.1');
        $product2->setMessage('Trajet sympathique!');
        $product2->setMusique('1');
        $product2->setPlace('2');
        $product2->setPrix('200');
        $product2->setType('1');
        $product2->setValid('1');
        $product2->setVehicule('206');
        $product2->setVillea('');
        $product2->setVilleb('Kharouba');
        $product2->setVue('4');
        $product2->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product2->setJours($this->getReference('jours2'));
        $manager->persist($product2);
        
        $product3 = new Product();
        $product3->setUser($this->getReference('user3'));
        $product3->setAnimal('1');
        $product3->setArrivee('31 - Oran');
        $product3->setBlabla('1');
        $product3->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product3->setDepart('16 - Alger');
        $product3->setFilles('0');
        $product3->setFumer('0');
        $product3->setHeure('09h');
        $product3->setIp('127.0.0.1');
        $product3->setMessage('Trajet sympathique!');
        $product3->setMusique('1');
        $product3->setPlace('2');
        $product3->setPrix('200');
        $product3->setType('1');
        $product3->setValid('1');
        $product3->setVehicule('206');
        $product3->setVillea('');
        $product3->setVilleb('Kharouba');
        $product3->setVue('4');
        $product3->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product3->setJours($this->getReference('jours3'));
        $manager->persist($product3);
        
        $product4 = new Product();
        $product4->setUser($this->getReference('user4'));
        $product4->setAnimal('1');
        $product4->setArrivee('31 - Oran');
        $product4->setBlabla('1');
        $product4->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product4->setDepart('16 - Alger');
        $product4->setFilles('0');
        $product4->setFumer('0');
        $product4->setHeure('09h');
        $product4->setIp('127.0.0.1');
        $product4->setMessage('Trajet sympathique!');
        $product4->setMusique('1');
        $product4->setPlace('2');
        $product4->setPrix('200');
        $product4->setType('1');
        $product4->setValid('1');
        $product4->setVehicule('206');
        $product4->setVillea('');
        $product4->setVilleb('Kharouba');
        $product4->setVue('4');
        $product4->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product4->setJours($this->getReference('jours4'));
        $manager->persist($product4);
        
        $product5 = new Product();
        $product5->setUser($this->getReference('user5'));
        $product5->setAnimal('1');
        $product5->setArrivee('31 - Oran');
        $product5->setBlabla('1');
        $product5->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product5->setDepart('16 - Alger');
        $product5->setFilles('0');
        $product5->setFumer('0');
        $product5->setHeure('09h');
        $product5->setIp('127.0.0.1');
        $product5->setMessage('Trajet sympathique!');
        $product5->setMusique('1');
        $product5->setPlace('2');
        $product5->setPrix('200');
        $product5->setType('1');
        $product5->setValid('1');
        $product5->setVehicule('206');
        $product5->setVillea('');
        $product5->setVilleb('Kharouba');
        $product5->setVue('4');
        $product5->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product5->setJours($this->getReference('jours5'));
        $manager->persist($product5);
        
        $product6 = new Product();
        $product6->setUser($this->getReference('user6'));
        $product6->setAnimal('1');
        $product6->setArrivee('31 - Oran');
        $product6->setBlabla('1');
        $product6->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product6->setDepart('16 - Alger');
        $product6->setFilles('0');
        $product6->setFumer('0');
        $product6->setHeure('09h');
        $product6->setIp('127.0.0.1');
        $product6->setMessage('Trajet sympathique!');
        $product6->setMusique('1');
        $product6->setPlace('2');
        $product6->setPrix('200');
        $product6->setType('1');
        $product6->setValid('1');
        $product6->setVehicule('206');
        $product6->setVillea('');
        $product6->setVilleb('Kharouba');
        $product6->setVue('4');
        $product6->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product6->setJours($this->getReference('jours6'));
        $manager->persist($product6);
        
        $product7 = new Product();
        $product7->setUser($this->getReference('user7'));
        $product7->setAnimal('1');
        $product7->setArrivee('31 - Oran');
        $product7->setBlabla('1');
        $product7->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product7->setDepart('16 - Alger');
        $product7->setFilles('0');
        $product7->setFumer('0');
        $product7->setHeure('09h');
        $product7->setIp('127.0.0.1');
        $product7->setMessage('Trajet sympathique!');
        $product7->setMusique('1');
        $product7->setPlace('2');
        $product7->setPrix('200');
        $product7->setType('1');
        $product7->setValid('1');
        $product7->setVehicule('206');
        $product7->setVillea('');
        $product7->setVilleb('Kharouba');
        $product7->setVue('4');
        $product7->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product7->setJours($this->getReference('jours7'));
        $manager->persist($product7);
        
        $product8 = new Product();
        $product8->setUser($this->getReference('user8'));
        $product8->setAnimal('1');
        $product8->setArrivee('31 - Oran');
        $product8->setBlabla('1');
        $product8->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product8->setDepart('16 - Alger');
        $product8->setFilles('0');
        $product8->setFumer('0');
        $product8->setHeure('09h');
        $product8->setIp('127.0.0.1');
        $product8->setMessage('Trajet sympathique!');
        $product8->setMusique('1');
        $product8->setPlace('2');
        $product8->setPrix('200');
        $product8->setType('1');
        $product8->setValid('1');
        $product8->setVehicule('206');
        $product8->setVillea('');
        $product8->setVilleb('Kharouba');
        $product8->setVue('4');
        $product8->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product8->setJours($this->getReference('jours8'));
        $manager->persist($product8);
        
        $product9 = new Product();
        $product9->setUser($this->getReference('user9'));
        $product9->setAnimal('1');
        $product9->setArrivee('31 - Oran');
        $product9->setBlabla('1');
        $product9->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product9->setDepart('16 - Alger');
        $product9->setFilles('0');
        $product9->setFumer('0');
        $product9->setHeure('09h');
        $product9->setIp('127.0.0.1');
        $product9->setMessage('Trajet sympathique!');
        $product9->setMusique('1');
        $product9->setPlace('2');
        $product9->setPrix('200');
        $product9->setType('1');
        $product9->setValid('1');
        $product9->setVehicule('206');
        $product9->setVillea('');
        $product9->setVilleb('Kharouba');
        $product9->setVue('4');
        $product9->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product9->setJours($this->getReference('jours9'));
        $manager->persist($product9);
        
        $product10 = new Product();
        $product10->setUser($this->getReference('user10'));
        $product10->setAnimal('1');
        $product10->setArrivee('31 - Oran');
        $product10->setBlabla('1');
        $product10->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product10->setDepart('16 - Alger');
        $product10->setFilles('0');
        $product10->setFumer('0');
        $product10->setHeure('09h');
        $product10->setIp('127.0.0.1');
        $product10->setMessage('Trajet sympathique!');
        $product10->setMusique('1');
        $product10->setPlace('2');
        $product10->setPrix('200');
        $product10->setType('1');
        $product10->setValid('1');
        $product10->setVehicule('206');
        $product10->setVillea('');
        $product10->setVilleb('Kharouba');
        $product10->setVue('4');
        $product10->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product10->setJours($this->getReference('jours10'));
        $manager->persist($product10);
        
        $product11 = new Product();
        $product11->setUser($this->getReference('user11'));
        $product11->setAnimal('1');
        $product11->setArrivee('31 - Oran');
        $product11->setBlabla('1');
        $product11->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product11->setDepart('16 - Alger');
        $product11->setFilles('0');
        $product11->setFumer('0');
        $product11->setHeure('09h');
        $product11->setIp('127.0.0.1');
        $product11->setMessage('Trajet sympathique!');
        $product11->setMusique('1');
        $product11->setPlace('2');
        $product11->setPrix('200');
        $product11->setType('1');
        $product11->setValid('1');
        $product11->setVehicule('206');
        $product11->setVillea('');
        $product11->setVilleb('Kharouba');
        $product11->setVue('4');
        $product11->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product11->setJours($this->getReference('jours11'));
        $manager->persist($product11);
        
        $product12 = new Product();
        $product12->setUser($this->getReference('user12'));
        $product12->setAnimal('1');
        $product12->setArrivee('31 - Oran');
        $product12->setBlabla('1');
        $product12->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product12->setDepart('16 - Alger');
        $product12->setFilles('0');
        $product12->setFumer('0');
        $product12->setHeure('09h');
        $product12->setIp('127.0.0.1');
        $product12->setMessage('Trajet sympathique!');
        $product12->setMusique('1');
        $product12->setPlace('2');
        $product12->setPrix('200');
        $product12->setType('1');
        $product12->setValid('1');
        $product12->setVehicule('206');
        $product12->setVillea('');
        $product12->setVilleb('Kharouba');
        $product12->setVue('4');
        $product12->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product12->setJours($this->getReference('jours12'));
        $manager->persist($product12);
        
        $product13 = new Product();
        $product13->setUser($this->getReference('user13'));
        $product13->setAnimal('1');
        $product13->setArrivee('31 - Oran');
        $product13->setBlabla('1');
        $product13->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product13->setDepart('16 - Alger');
        $product13->setFilles('0');
        $product13->setFumer('0');
        $product13->setHeure('09h');
        $product13->setIp('127.0.0.1');
        $product13->setMessage('Trajet sympathique!');
        $product13->setMusique('1');
        $product13->setPlace('2');
        $product13->setPrix('200');
        $product13->setType('1');
        $product13->setValid('1');
        $product13->setVehicule('206');
        $product13->setVillea('');
        $product13->setVilleb('Kharouba');
        $product13->setVue('4');
        $product13->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product13->setJours($this->getReference('jours13'));
        $manager->persist($product13);
        
        $product14 = new Product();
        $product14->setUser($this->getReference('user1'));
        $product14->setAnimal('1');
        $product14->setArrivee('31 - Oran');
        $product14->setBlabla('1');
        $product14->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product14->setDepart('16 - Alger');
        $product14->setFilles('0');
        $product14->setFumer('0');
        $product14->setHeure('09h');
        $product14->setIp('127.0.0.1');
        $product14->setMessage('Trajet sympathique!');
        $product14->setMusique('1');
        $product14->setPlace('2');
        $product14->setPrix('200');
        $product14->setType('1');
        $product14->setValid('1');
        $product14->setVehicule('206');
        $product14->setVillea('');
        $product14->setVilleb('Kharouba');
        $product14->setVue('4');
        $product14->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product14->setJours($this->getReference('jours14'));
        $manager->persist($product14);
        
        $product15 = new Product();
        $product15->setUser($this->getReference('user14'));
        $product15->setAnimal('1');
        $product15->setArrivee('31 - Oran');
        $product15->setBlabla('1');
        $product15->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product15->setDepart('16 - Alger');
        $product15->setFilles('0');
        $product15->setFumer('0');
        $product15->setHeure('09h');
        $product15->setIp('127.0.0.1');
        $product15->setMessage('Trajet sympathique!');
        $product15->setMusique('1');
        $product15->setPlace('2');
        $product15->setPrix('200');
        $product15->setType('1');
        $product15->setValid('1');
        $product15->setVehicule('206');
        $product15->setVillea('');
        $product15->setVilleb('Kharouba');
        $product15->setVue('4');
        $product15->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product15->setJours($this->getReference('jours15'));
        $manager->persist($product15);
        
        $product16 = new Product();
        $product16->setUser($this->getReference('user15'));
        $product16->setAnimal('1');
        $product16->setArrivee('31 - Oran');
        $product16->setBlabla('1');
        $product16->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product16->setDepart('16 - Alger');
        $product16->setFilles('0');
        $product16->setFumer('0');
        $product16->setHeure('09h');
        $product16->setIp('127.0.0.1');
        $product16->setMessage('Trajet sympathique!');
        $product16->setMusique('1');
        $product16->setPlace('2');
        $product16->setPrix('200');
        $product16->setType('1');
        $product16->setValid('1');
        $product16->setVehicule('206');
        $product16->setVillea('');
        $product16->setVilleb('Kharouba');
        $product16->setVue('4');
        $product16->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product16->setJours($this->getReference('jours16'));
        $manager->persist($product16);
        
        $product17 = new Product();
        $product17->setUser($this->getReference('user1'));
        $product17->setAnimal('1');
        $product17->setArrivee('31 - Oran');
        $product17->setBlabla('1');
        $product17->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product17->setDepart('16 - Alger');
        $product17->setFilles('0');
        $product17->setFumer('0');
        $product17->setHeure('09h');
        $product17->setIp('127.0.0.1');
        $product17->setMessage('Trajet sympathique!');
        $product17->setMusique('1');
        $product17->setPlace('2');
        $product17->setPrix('200');
        $product17->setType('1');
        $product17->setValid('1');
        $product17->setVehicule('206');
        $product17->setVillea('');
        $product17->setVilleb('Kharouba');
        $product17->setVue('4');
        $product17->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product17->setJours($this->getReference('jours17'));
        $manager->persist($product17);
        
        $product18 = new Product();
        $product18->setUser($this->getReference('user2'));
        $product18->setAnimal('1');
        $product18->setArrivee('31 - Oran');
        $product18->setBlabla('1');
        $product18->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product18->setDepart('16 - Alger');
        $product18->setFilles('0');
        $product18->setFumer('0');
        $product18->setHeure('09h');
        $product18->setIp('127.0.0.1');
        $product18->setMessage('Trajet sympathique!');
        $product18->setMusique('1');
        $product18->setPlace('2');
        $product18->setPrix('200');
        $product18->setType('1');
        $product18->setValid('1');
        $product18->setVehicule('206');
        $product18->setVillea('');
        $product18->setVilleb('Kharouba');
        $product18->setVue('4');
        $product18->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product18->setJours($this->getReference('jours18'));
        $manager->persist($product18);
        
        $product19 = new Product();
        $product19->setUser($this->getReference('user3'));
        $product19->setAnimal('1');
        $product19->setArrivee('31 - Oran');
        $product19->setBlabla('1');
        $product19->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product19->setDepart('16 - Alger');
        $product19->setFilles('0');
        $product19->setFumer('0');
        $product19->setHeure('09h');
        $product19->setIp('127.0.0.1');
        $product19->setMessage('Trajet sympathique!');
        $product19->setMusique('1');
        $product19->setPlace('2');
        $product19->setPrix('200');
        $product19->setType('1');
        $product19->setValid('1');
        $product19->setVehicule('206');
        $product19->setVillea('');
        $product19->setVilleb('Kharouba');
        $product19->setVue('4');
        $product19->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product19->setJours($this->getReference('jours19'));
        $manager->persist($product19);
        
        $product20 = new Product();
        $product20->setUser($this->getReference('user1'));
        $product20->setAnimal('1');
        $product20->setArrivee('31 - Oran');
        $product20->setBlabla('1');
        $product20->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product20->setDepart('16 - Alger');
        $product20->setFilles('0');
        $product20->setFumer('0');
        $product20->setHeure('09h');
        $product20->setIp('127.0.0.1');
        $product20->setMessage('Trajet sympathique!');
        $product20->setMusique('1');
        $product20->setPlace('2');
        $product20->setPrix('200');
        $product20->setType('1');
        $product20->setValid('1');
        $product20->setVehicule('206');
        $product20->setVillea('');
        $product20->setVilleb('Kharouba');
        $product20->setVue('4');
        $product20->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product20->setJours($this->getReference('jours20'));
        $manager->persist($product20);
        
        $product21 = new Product();
        $product21->setUser($this->getReference('user2'));
        $product21->setAnimal('1');
        $product21->setArrivee('31 - Oran');
        $product21->setBlabla('1');
        $product21->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product21->setDepart('16 - Alger');
        $product21->setFilles('0');
        $product21->setFumer('0');
        $product21->setHeure('09h');
        $product21->setIp('127.0.0.1');
        $product21->setMessage('Trajet sympathique!');
        $product21->setMusique('1');
        $product21->setPlace('2');
        $product21->setPrix('200');
        $product21->setType('1');
        $product21->setValid('1');
        $product21->setVehicule('206');
        $product21->setVillea('');
        $product21->setVilleb('Kharouba');
        $product21->setVue('4');
        $product21->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product21->setJours($this->getReference('jours21'));
        $manager->persist($product21);
        
        $product22 = new Product();
        $product22->setUser($this->getReference('user11'));
        $product22->setAnimal('1');
        $product22->setArrivee('31 - Oran');
        $product22->setBlabla('1');
        $product22->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product22->setDepart('16 - Alger');
        $product22->setFilles('0');
        $product22->setFumer('0');
        $product22->setHeure('09h');
        $product22->setIp('127.0.0.1');
        $product22->setMessage('Trajet sympathique!');
        $product22->setMusique('1');
        $product22->setPlace('2');
        $product22->setPrix('200');
        $product22->setType('1');
        $product22->setValid('1');
        $product22->setVehicule('206');
        $product22->setVillea('');
        $product22->setVilleb('Kharouba');
        $product22->setVue('4');
        $product22->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product22->setJours($this->getReference('jours22'));
        $manager->persist($product22);
        
        $product23 = new Product();
        $product23->setUser($this->getReference('user13'));
        $product23->setAnimal('1');
        $product23->setArrivee('31 - Oran');
        $product23->setBlabla('1');
        $product23->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product23->setDepart('16 - Alger');
        $product23->setFilles('0');
        $product23->setFumer('0');
        $product23->setHeure('09h');
        $product23->setIp('127.0.0.1');
        $product23->setMessage('Trajet sympathique!');
        $product23->setMusique('1');
        $product23->setPlace('2');
        $product23->setPrix('200');
        $product23->setType('1');
        $product23->setValid('1');
        $product23->setVehicule('206');
        $product23->setVillea('');
        $product23->setVilleb('Kharouba');
        $product23->setVue('4');
        $product23->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product23->setJours($this->getReference('jours23'));
        $manager->persist($product23);
        
        $product24 = new Product();
        $product24->setUser($this->getReference('user12'));
        $product24->setAnimal('1');
        $product24->setArrivee('31 - Oran');
        $product24->setBlabla('1');
        $product24->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product24->setDepart('16 - Alger');
        $product24->setFilles('0');
        $product24->setFumer('0');
        $product24->setHeure('09h');
        $product24->setIp('127.0.0.1');
        $product24->setMessage('Trajet sympathique!');
        $product24->setMusique('1');
        $product24->setPlace('2');
        $product24->setPrix('200');
        $product24->setType('1');
        $product24->setValid('1');
        $product24->setVehicule('206');
        $product24->setVillea('');
        $product24->setVilleb('Kharouba');
        $product24->setVue('4');
        $product24->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product24->setJours($this->getReference('jours24'));
        $manager->persist($product24);
        
        $product25 = new Product();
        $product25->setUser($this->getReference('user6'));
        $product25->setAnimal('1');
        $product25->setArrivee('31 - Oran');
        $product25->setBlabla('1');
        $product25->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product25->setDepart('16 - Alger');
        $product25->setFilles('0');
        $product25->setFumer('0');
        $product25->setHeure('09h');
        $product25->setIp('127.0.0.1');
        $product25->setMessage('Trajet sympathique!');
        $product25->setMusique('1');
        $product25->setPlace('2');
        $product25->setPrix('200');
        $product25->setType('1');
        $product25->setValid('1');
        $product25->setVehicule('206');
        $product25->setVillea('');
        $product25->setVilleb('Kharouba');
        $product25->setVue('4');
        $product25->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product25->setJours($this->getReference('jours25'));
        $manager->persist($product25);
        
        $product26 = new Product();
        $product26->setUser($this->getReference('user7'));
        $product26->setAnimal('1');
        $product26->setArrivee('31 - Oran');
        $product26->setBlabla('1');
        $product26->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product26->setDepart('16 - Alger');
        $product26->setFilles('0');
        $product26->setFumer('0');
        $product26->setHeure('09h');
        $product26->setIp('127.0.0.1');
        $product26->setMessage('Trajet sympathique!');
        $product26->setMusique('1');
        $product26->setPlace('2');
        $product26->setPrix('200');
        $product26->setType('1');
        $product26->setValid('1');
        $product26->setVehicule('206');
        $product26->setVillea('');
        $product26->setVilleb('Kharouba');
        $product26->setVue('4');
        $product26->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product26->setJours($this->getReference('jours26'));
        $manager->persist($product26);
        
        $product27 = new Product();
        $product27->setUser($this->getReference('user8'));
        $product27->setAnimal('1');
        $product27->setArrivee('31 - Oran');
        $product27->setBlabla('1');
        $product27->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product27->setDepart('16 - Alger');
        $product27->setFilles('0');
        $product27->setFumer('0');
        $product27->setHeure('09h');
        $product27->setIp('127.0.0.1');
        $product27->setMessage('Trajet sympathique!');
        $product27->setMusique('1');
        $product27->setPlace('2');
        $product27->setPrix('200');
        $product27->setType('1');
        $product27->setValid('1');
        $product27->setVehicule('206');
        $product27->setVillea('');
        $product27->setVilleb('Kharouba');
        $product27->setVue('4');
        $product27->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product27->setJours($this->getReference('jours27'));
        $manager->persist($product27);
        
        $product28 = new Product();
        $product28->setUser($this->getReference('user9'));
        $product28->setAnimal('1');
        $product28->setArrivee('31 - Oran');
        $product28->setBlabla('1');
        $product28->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product28->setDepart('16 - Alger');
        $product28->setFilles('0');
        $product28->setFumer('0');
        $product28->setHeure('09h');
        $product28->setIp('127.0.0.1');
        $product28->setMessage('Trajet sympathique!');
        $product28->setMusique('1');
        $product28->setPlace('2');
        $product28->setPrix('200');
        $product28->setType('1');
        $product28->setValid('1');
        $product28->setVehicule('206');
        $product28->setVillea('');
        $product28->setVilleb('Kharouba');
        $product28->setVue('4');
        $product28->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product28->setJours($this->getReference('jours28'));
        $manager->persist($product28);
        
        $product29 = new Product();
        $product29->setUser($this->getReference('user10'));
        $product29->setAnimal('1');
        $product29->setArrivee('31 - Oran');
        $product29->setBlabla('1');
        $product29->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product29->setDepart('16 - Alger');
        $product29->setFilles('0');
        $product29->setFumer('0');
        $product29->setHeure('09h');
        $product29->setIp('127.0.0.1');
        $product29->setMessage('Trajet sympathique!');
        $product29->setMusique('1');
        $product29->setPlace('2');
        $product29->setPrix('200');
        $product29->setType('1');
        $product29->setValid('1');
        $product29->setVehicule('206');
        $product29->setVillea('');
        $product29->setVilleb('Kharouba');
        $product29->setVue('4');
        $product29->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product29->setJours($this->getReference('jours29'));
        $manager->persist($product29);
        
        $product30 = new Product();
        $product30->setUser($this->getReference('user11'));
        $product30->setAnimal('1');
        $product30->setArrivee('31 - Oran');
        $product30->setBlabla('1');
        $product30->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product30->setDepart('16 - Alger');
        $product30->setFilles('0');
        $product30->setFumer('0');
        $product30->setHeure('09h');
        $product30->setIp('127.0.0.1');
        $product30->setMessage('Trajet sympathique!');
        $product30->setMusique('1');
        $product30->setPlace('2');
        $product30->setPrix('200');
        $product30->setType('1');
        $product30->setValid('1');
        $product30->setVehicule('206');
        $product30->setVillea('');
        $product30->setVilleb('Kharouba');
        $product30->setVue('4');
        $product30->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product30->setJours($this->getReference('jours30'));
        $manager->persist($product30);
        
        $product31 = new Product();
        $product31->setUser($this->getReference('user4'));
        $product31->setAnimal('1');
        $product31->setArrivee('31 - Oran');
        $product31->setBlabla('1');
        $product31->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product31->setDepart('16 - Alger');
        $product31->setFilles('0');
        $product31->setFumer('0');
        $product31->setHeure('09h');
        $product31->setIp('127.0.0.1');
        $product31->setMessage('Trajet sympathique!');
        $product31->setMusique('1');
        $product31->setPlace('2');
        $product31->setPrix('200');
        $product31->setType('1');
        $product31->setValid('1');
        $product31->setVehicule('206');
        $product31->setVillea('');
        $product31->setVilleb('Kharouba');
        $product31->setVue('4');
        $product31->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product31->setJours($this->getReference('jours31'));
        $manager->persist($product31);
        
        $product32 = new Product();
        $product32->setUser($this->getReference('user5'));
        $product32->setAnimal('1');
        $product32->setArrivee('31 - Oran');
        $product32->setBlabla('1');
        $product32->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product32->setDepart('16 - Alger');
        $product32->setFilles('0');
        $product32->setFumer('0');
        $product32->setHeure('09h');
        $product32->setIp('127.0.0.1');
        $product32->setMessage('Trajet sympathique!');
        $product32->setMusique('1');
        $product32->setPlace('2');
        $product32->setPrix('200');
        $product32->setType('1');
        $product32->setValid('1');
        $product32->setVehicule('206');
        $product32->setVillea('');
        $product32->setVilleb('Kharouba');
        $product32->setVue('4');
        $product32->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product32->setJours($this->getReference('jours32'));
        $manager->persist($product32);
        
        $product33 = new Product();
        $product33->setUser($this->getReference('user8'));
        $product33->setAnimal('1');
        $product33->setArrivee('31 - Oran');
        $product33->setBlabla('1');
        $product33->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product33->setDepart('16 - Alger');
        $product33->setFilles('0');
        $product33->setFumer('0');
        $product33->setHeure('09h');
        $product33->setIp('127.0.0.1');
        $product33->setMessage('Trajet sympathique!');
        $product33->setMusique('1');
        $product33->setPlace('2');
        $product33->setPrix('200');
        $product33->setType('1');
        $product33->setValid('1');
        $product33->setVehicule('206');
        $product33->setVillea('');
        $product33->setVilleb('Kharouba');
        $product33->setVue('4');
        $product33->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product33->setJours($this->getReference('jours33'));
        $manager->persist($product33);
        
        $product34 = new Product();
        $product34->setUser($this->getReference('user9'));
        $product34->setAnimal('1');
        $product34->setArrivee('31 - Oran');
        $product34->setBlabla('1');
        $product34->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product34->setDepart('16 - Alger');
        $product34->setFilles('0');
        $product34->setFumer('0');
        $product34->setHeure('09h');
        $product34->setIp('127.0.0.1');
        $product34->setMessage('Trajet sympathique!');
        $product34->setMusique('1');
        $product34->setPlace('2');
        $product34->setPrix('200');
        $product34->setType('1');
        $product34->setValid('1');
        $product34->setVehicule('206');
        $product34->setVillea('');
        $product34->setVilleb('Kharouba');
        $product34->setVue('4');
        $product34->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product34->setJours($this->getReference('jours34'));
        $manager->persist($product34);
        
        $product35 = new Product();
        $product35->setUser($this->getReference('user3'));
        $product35->setAnimal('1');
        $product35->setArrivee('31 - Oran');
        $product35->setBlabla('1');
        $product35->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product35->setDepart('16 - Alger');
        $product35->setFilles('0');
        $product35->setFumer('0');
        $product35->setHeure('09h');
        $product35->setIp('127.0.0.1');
        $product35->setMessage('Trajet sympathique!');
        $product35->setMusique('1');
        $product35->setPlace('2');
        $product35->setPrix('200');
        $product35->setType('1');
        $product35->setValid('1');
        $product35->setVehicule('206');
        $product35->setVillea('');
        $product35->setVilleb('Kharouba');
        $product35->setVue('4');
        $product35->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product35->setJours($this->getReference('jours35'));
        $manager->persist($product35);
        
        $product36 = new Product();
        $product36->setUser($this->getReference('user4'));
        $product36->setAnimal('1');
        $product36->setArrivee('31 - Oran');
        $product36->setBlabla('1');
        $product36->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product36->setDepart('16 - Alger');
        $product36->setFilles('0');
        $product36->setFumer('0');
        $product36->setHeure('09h');
        $product36->setIp('127.0.0.1');
        $product36->setMessage('Trajet sympathique!');
        $product36->setMusique('1');
        $product36->setPlace('2');
        $product36->setPrix('200');
        $product36->setType('1');
        $product36->setValid('1');
        $product36->setVehicule('206');
        $product36->setVillea('');
        $product36->setVilleb('Kharouba');
        $product36->setVue('4');
        $product36->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product36->setJours($this->getReference('jours36'));
        $manager->persist($product36);
        
        $product37 = new Product();
        $product37->setUser($this->getReference('user1'));
        $product37->setAnimal('1');
        $product37->setArrivee('31 - Oran');
        $product37->setBlabla('1');
        $product37->setDate(new \DateTime('2015-01-31 00:00:00'));
        $product37->setDepart('16 - Alger');
        $product37->setFilles('0');
        $product37->setFumer('0');
        $product37->setHeure('09h');
        $product37->setIp('127.0.0.1');
        $product37->setMessage('Trajet sympathique!');
        $product37->setMusique('1');
        $product37->setPlace('2');
        $product37->setPrix('200');
        $product37->setType('1');
        $product37->setValid('1');
        $product37->setVehicule('206');
        $product37->setVillea('');
        $product37->setVilleb('Kharouba');
        $product37->setVue('4');
        $product37->setDeposit(new \DateTime('2015-01-31 00:00:00'));
        $product37->setJours($this->getReference('jours37'));
        $manager->persist($product37);
        
        $manager->flush();
        
        $this->addReference('product1',  $product1);
        $this->addReference('product2',  $product2);
        $this->addReference('product3',  $product3);
        $this->addReference('product4',  $product4);
        $this->addReference('product5',  $product5);
        $this->addReference('product6',  $product6);
        $this->addReference('product7',  $product7);
        $this->addReference('product8',  $product8);
        $this->addReference('product9',  $product9);
        $this->addReference('product10', $product10);
        $this->addReference('product11', $product11);
        $this->addReference('product12', $product12);
        $this->addReference('product13', $product13);
        $this->addReference('product14', $product14);
        $this->addReference('product15', $product15);
        $this->addReference('product16', $product16);
        $this->addReference('product17', $product17);
        $this->addReference('product18', $product18);
        $this->addReference('product19', $product19);
        $this->addReference('product20', $product20);
        $this->addReference('product21', $product21);
        $this->addReference('product22', $product22);
        $this->addReference('product23', $product23);
        $this->addReference('product24', $product24);
        $this->addReference('product25', $product25);
        $this->addReference('product26', $product26);
        $this->addReference('product27', $product27);
        $this->addReference('product28', $product28);
        $this->addReference('product29', $product29);
        $this->addReference('product30', $product30);
        $this->addReference('product31', $product31);
        $this->addReference('product32', $product32);
        $this->addReference('product33', $product33);
        $this->addReference('product34', $product34);
        $this->addReference('product35', $product35);
        $this->addReference('product36', $product36);
        $this->addReference('product37', $product37);
    }
    
    public function getOrder()
    {
        return 3; // l'ordre dans lequel les fichiers sont chargés
    }
}
