<?php

namespace Base\NrohoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SortieBledvoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieBledvoyageRepository extends EntityRepository
{
}
